site_name: Firefly Playground

# Repository
repo_name: firefly-playground
repo_url: https://github.com/venafi/firefly-playground
edit_uri: ""


theme:
  icon:
    logo: fontawesome/solid/arrow-up-right-from-square
  name: material
  features:
    - content.code.annotate
    - navigation.expand
    - content.tabs.link
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

copyright: Copyright &copy; 2024 Venafi

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true     

plugins:
    - search
    #- macros
    - tags
    #- glightbox  
    #- mike:
        # these fields are all optional; the defaults are as below...
     #   version_selector: true   # set to false to leave out the version selector
     #   css_dir: css             # the directory to put the version selector's CSS
     #   javascript_dir: js       # the directory to put the version selector's JS
     #   canonical_version: null  # the version for <link rel="canonical">; `null`
                               # uses the version specified via `mike deploy`

# nav:
#   - Edge:
#     - About: edgeca/edgeca.md
#     - Requirements: edgeca/deploying-edgeca.md
#     - Deployment Options: 
#       - Standalone Binary: todo.md
#       - Docker: edgeca/docker.md
#     - Configuration: edgeca/configuration.md  
#     - Quick Start: todo.md
#     - Example Use Cases:
#       - TPP/VaaS policy router: edgeca/tpp-policy_router.md
#       - In-memory Delegated Issuer: edgeca/tpp-subca.md
#       - Pub/Sub Issuer: edgeca/pub-sub.md
#       - GraphQL Machine Identity Gateway : edgeca/graphql-gateway.md
#       - Maintain State (Blockchain) : edgeca/state.md
      
#   - EdgeAuth:
#     - Configuration:
#       - page: edgeauth/Deploying_EdgeAuth.md
#     - Page 1: section/page-1.md
#     - Page n: section/page-n.md
    
#   - Scatch: edgeca/scratch.md
     
extra:
    version:
      provider: mike
      default: latest
    component_name: Firefly
    price: 12.50
    company:
        name: Acme
        address: 1234
        website: 12333333e3wrwrw4e