bootstrap:
  vaas:
    url: https://api.venafi.cloud
    auth:
      privateKeyFile: /etc/firefly/private-key.pem
      clientID: a6498bb7-c804-11ee-bcff-7a10aefd838f
    csr:
      instanceNaming: Demo
server:
  rest:
    port: 8281
    tls:
      dnsNames:
      - firefly.venafi.example
      ipAddress: 127.0.0.1
