bootstrap:
  vaas:
    url: https://api.venafi.cloud
    auth:
      privateKeyFile: /etc/firefly/private-key.pem
      clientID: c9724b02-c075-11ee-8612-3219894022c0
    csr:
      instanceNaming: Demo
server:
  rest:
    port: 8281
    tls:
      dnsNames:
      - firefly.venafi.example
      ipAddress: 127.0.0.1
