bootstrap:
  vaas:
    url: https://api.venafi.cloud
    auth:
      privateKeyFile: /etc/firefly/private-key.pem
      clientID: f531953f-c51c-11ee-aa38-62722f50b33a
    csr:
      instanceNaming: Demo
server:
  grpc:
    uds:
      socketPath: /opt/firefly/grpc.sock
