bootstrap:
  selfSigned:
    csr:
      commonName: Firefly Playground
      privateKey:
        algorithm: EC
        size: P256
      duration: PT8760H # one year
    trustRootDirectory: /etc/firefly/trust
signer:
  inMemory: true
server:
  rest:
    port: 8281
    tls:
      dnsNames:
      - firefly.venafi.example
      ipAddress: 127.0.0.1
  authentication:
    jwt:
#      oidc:
#        baseUrl: http://superfuzz.venafi.example:8000
#        audience: firefly
      jwks:
        urls:
        - http://jwt-this.example:8000/.well-known/jwks.json
  authorization:
    configuration: Firefly Playground

policies:
- name: Firefly Playground
  keyUsages:
  - digitalSignature
  - keyEncipherment
  extendedKeyUsages:
  - SERVER_AUTH
  keyAlgorithm:
    allowedValues:
    - EC_P256
    - EC_P384
    - EC_P521
    defaultValue: EC_P256
  validityPeriod: P7D